name: Review Build URL

on:
  pull_request:
    branches:
      - feature/**

jobs:
  post_build_url:
    name: sample comment
    runs-on: ubuntu-latest
    steps:
      - name: Post Review Build URL
        uses: unsplash/comment-on-pr@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          msg: "Build URL: https://${{ steps.get-branch-name-sanitized.outputs.branch }}.fightpandemics.xyz"
          check_for_duplicate_msg: true
